In [14]:
# 1st answer
def function(x,y):
    try:
        result= x/y
    except:
        print("not divisible by 5")
        
function(5,0)

    

not divisible by 5


In [25]:
#2nd nswer
subjects=["Americans ","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"] 
print(subjects,verbs,objects)
p = [(a+" "+b+" "+c) for a in subjects 
    for b in verbs
    for c in objects]
for i in p:
    print(i)
 

['Americans ', 'Indians'] ['play', 'watch'] ['Baseball', 'Cricket']
Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [33]:
# 3rd answer
import numpy as np
a = np.array([1,2,3,4,6])
b = 3
mat = np.column_stack([a**(b-i-1) for  i in range(b)])
print(mat)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [36  6  1]]
